/*
 * Copyright (C) 2019 Philip Mortimer
 *
 * This file is part of Philip Mortimer Example Programs.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package shared.gui.function_of_x;

import javafx.stage.Stage;

/**
 * Base class of the controller classes for function of x GUI applications such 
 * as QuadraticCurve. It causes the application's view to appear, and responds 
 * to click's of the view's 'Redraw' button.
 */
public abstract class FunctionOfXController {
    private final FunctionOfXView view;
        
    public FunctionOfXController(FunctionOfXView view) {
        this.view = view;
        this.view.setRedrawAction(e -> onRedraw());
    }

    /**
     * Generates the output in the view. This includes drawing the line chart.
     */
    public abstract void generateOutput();
    
    /**
     * Called when the user clicks the 'Redraw' button. It calls the {@link 
     * #generateOutput() generateOutput} method if there are no
     * errors in the data in the view's input fields.
     */
    private void onRedraw() {
        if (view.retrieveInputData()) {
            generateOutput();
        }
    }
        
    /**
     * Causes the application's view to appear containing output
     * generated by initial call to {@link #generateOutput() generateOutput}.
     * 
     * @param stage JavaFX Stage object passed to the JavaFX Application
     * object's start method.
     */
    public void start(Stage stage) {
        generateOutput();
        this.view.show(stage);
    }        
}
